// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDog6QISLjgbwgypqw11d2vl8kvmFVwLSw',
    appId: '1:931656574267:android:e63638eaf0dce348b9c31e',
    messagingSenderId: '931656574267',
    projectId: 'glennverse-3cf94',
    storageBucket: 'glennverse-3cf94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsFXvzxyyKeSeBrr1Xdk_8fzlR5NogTko',
    appId: '1:931656574267:ios:04f78955579127f1b9c31e',
    messagingSenderId: '931656574267',
    projectId: 'glennverse-3cf94',
    storageBucket: 'glennverse-3cf94.firebasestorage.app',
    iosBundleId: 'com.glennverse.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVnhhni3pVPp-eH12N-GbXrpxqEFmEfpo',
    appId: '1:931656574267:web:c6399bb68afa39b9b9c31e',
    messagingSenderId: '931656574267',
    projectId: 'glennverse-3cf94',
    authDomain: 'glennverse-3cf94.firebaseapp.com',
    storageBucket: 'glennverse-3cf94.firebasestorage.app',
  );

}